### ISSUE TITLE
Folders change color

### ISSUE THREAD

**Issue by Xorok** [afollestad/cabinet#187] opened 2015-02-05 21:49 UTC
Some of the visible folders are blue (is this intentional?) but as soon as you open a folder and then go back they're grey too.
(-Apparently-depending-on-the-first-letter-in-their-name...-
*Changes every time you switch folders and go back)

![screenshot_2015-02-05-22-43-10](https://cloud.githubusercontent.com/assets/9898278/6069986/36d361a4-ad89-11e4-9245-407c22b39acd.png)
![screenshot_2015-02-05-22-43-15](https://cloud.githubusercontent.com/assets/9898278/6069993/4571efdc-ad89-11e4-96d6-056b8f4a96af.png)

**Comment by afollestad** [comment] 2015-02-05 21:51
Hmmm, that's definitely not intentional. Thanks for reporting this.

**Comment by Xorok** [comment] 2015-02-06 01:56
No problem :)

**Comment by afollestad** [comment] 2015-02-09 23:03
Does this happen with the latest version? Is there any noticeable triggers?

**Comment by afollestad** [comment] 2015-02-10 04:43
Closing this for now since I can't reproduce it.

**Closed by afollestad** 2015-02-10 04:43 UTC
Labels: can't reproduce
